需要提前下载好 gitlab/gitlab-ce:latest

version: '3.1'
services:
  gitlab:
    image: 'gitlab/gitlab-ce'
    container_name: gitlab
    restart: always
    hostname: 'gitlab.bmw.com'
    environment:
      GITLAB_OMNIBUS_CONFIG:
        external_url 'http://127.16.219.135'

    ports:
      - '10086:80'
      - '2224:22'
      - '443:443'
    volumes:
      - './config:/etc/gitlab'
      - './logs:/var/log/gitlab'
      - './data:/var/opt/gitlab'


查看 root password :

root@gitlab:/# cat /etc/gitlab/initial_root_password 
# WARNING: This value is valid only in the following conditions
#          1. If provided manually (either via `GITLAB_ROOT_PASSWORD` environment variable or via `gitlab_rails['initial_root_password']` setting in `gitlab.rb`, it was provided before database was seeded for the first time (usually, the first reconfigure run).
#          2. Password hasn't been changed manually, either via UI or via command line.
#
#          If the password shown here doesn't work, you must reset the admin password following https://docs.gitlab.com/ee/security/reset_user_password.html#reset-your-root-password.

Password: Ck/zYyIlazJjPh40kzJwZ8LDKPqtGFk4axVli4MXU+I=


